language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  postgresql: "9.3"
  
before_install:
  - git clone --quiet https://github.com/gaixie/jibu-schema.git $HOME/jibu-schema
  # 如果当前集成的分支是 develop，将 jibu-schema 项目的分支也 checkout 到 develop 上。  
  - if [[ $TRAVIS_BRANCH == 'develop' ]]; then git -C $HOME/jibu-schema/ checkout --track origin/develop; fi
  
before_script:
  - psql -c "CREATE USER jibu_db_user WITH PASSWORD '000000';" -U postgres
  - psql -c "CREATE DATABASE jibu_db OWNER jibu_db_user ENCODING 'UTF8';" -U postgres
  
  # ./jibu-schema/postgresql/tables/ 目录下的 .sql 文件按文件名顺序执行。
  - cat $HOME/jibu-schema/postgresql/tables/tables*.sql > $HOME/schema.sql
  - cat $HOME/jibu-schema/postgresql/tables/comments*.sql >> $HOME/schema.sql
  - psql -U $USER -d $DBNAME -1 -f $HOME/schema.sql
  
branches:
  only:
    - master
    - develop